### ISSUE TITLE
Error in highlight.sector.

### ISSUE THREAD

**Issue by danielruss** [xgaoo/ClusterMap#2]
Hello,
  My collaborators and I are attempting to run Cluster map on our data, and we are getting the error:
Error in highlight.sector(paste0(n, "_", names(cell_perc_list[[n]])),  : 
  `chr` contains index that does not beling to available sectors.

I have stepped through the code and found where the error occurs.
in highlight.sector in line 7 it check that all sector indecies are found in the index list. 

     if (!all(sector.index %in% sectors)) {
         stop("`chr` contains index that does not beling to available sectors.")
     }

     > sectors
     [1] "A_condition.0"  "A_condition.1"  "A_condition.2"  "A_condition.3"  "A_condition.4" "A_condition.5"  "A_condition.6"  "A_condition.7"  "A_condition.8" 
     [10] "A_condition.9"  "A_condition.10" "A_condition.11" "A_condition.12" "A_condition.13" "A_condition.14" "A_condition.15" "B_condition.0"  "B_condition.1" 
     [19] "B_condition.2"  "B_condition.3"  "B_condition.4"  "B_condition.5"  "B_condition.6"  "B_condition.7"  "B_condition.8"  "B_condition.9"  "B_condition.10"
     [28] "B_condition.11" "B_condition.12" "B_condition.13" "B_condition.14"

     >sector.index
     [1] "A.condition_0"  "A.condition_1"  "A.condition_2"  "A.condition_3"  "A.condition_4"  "A.condition_5"  "A.condition_6"  "A.condition_7"  "A.condition_8" 
     [10] "A.condition_9"  "A.condition_10" "A.condition_11" "A.condition_12" "A.condition_13" "A.condition_14" "A.condition_15"`

It appears that the code is changing the name of some of the sectors, but not the others.

The mapRes is 

     > mapRes
           A.condition    B.condition similarity regroup
     1   A.condition_5  B.condition_4       0.65       1
     2   A.condition_4  B.condition_3       0.63       2
     3   A.condition_3  B.condition_2       0.62       3
     4   A.condition_6  B.condition_8       0.61       4
     5  A.condition_13 B.condition_14       0.60       5
     6   A.condition_1  B.condition_1       0.60       6
     7   A.condition_2  B.condition_0       0.58       7
     8   A.condition_8  B.condition_7       0.55       8
     9   A.condition_0  B.condition_6       0.55       9
     10 A.condition_12 B.condition_11       0.54      10
     11 A.condition_10 B.condition_12       0.40      11
     12  A.condition_9  B.condition_9       0.40      12
     13 A.condition_11 B.condition_10       0.30      13
     14 A.condition_14           <NA>         NA      14
     15 A.condition_15           <NA>         NA      15
     16  A.condition_7           <NA>         NA      16
     17           <NA> B.condition_13         NA      17
     18           <NA>  B.condition_5         NA      18

Thank you,

**Comment by xgaoo** [comment]
Hello,

Thank you for trying our package. Sorry for the late response, I’m changing job. Could you please send me the code you run that generate the error? When you say “It appears that the code is changing the name of some of the sectors, but not the others.”, which name were not changed?

Thank you,

Xin


发件人: danielruss<mailto:notifications@github.com>
发送时间: 2018年10月5日 0:24
收件人: xgaoo/ClusterMap<mailto:ClusterMap@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [xgaoo/ClusterMap] Error in highlight.sector. (#2)


Hello,
My collaborators and I are attempting to run Cluster map on our data, and we are getting the error:
Error in highlight.sector(paste0(n, "_", names(cell_perc_list[[n]])), :
chr contains index that does not beling to available sectors.

I have stepped through the code and found where the error occurs.
in highlight.sector in line 7 it check that all sector indecies are found in the index list.

 if (!all(sector.index %in% sectors)) {
     stop("`chr` contains index that does not beling to available sectors.")
 }



 > sectors
 [1] "A_condition.0"  "A_condition.1"  "A_condition.2"  "A_condition.3"  "A_condition.4" "A_condition.5"  "A_condition.6"  "A_condition.7"  "A_condition.8"
 [10] "A_condition.9"  "A_condition.10" "A_condition.11" "A_condition.12" "A_condition.13" "A_condition.14" "A_condition.15" "B_condition.0"  "B_condition.1"
 [19] "B_condition.2"  "B_condition.3"  "B_condition.4"  "B_condition.5"  "B_condition.6"  "B_condition.7"  "B_condition.8"  "B_condition.9"  "B_condition.10"
 [28] "B_condition.11" "B_condition.12" "B_condition.13" "B_condition.14"

 >sector.index
 [1] "A.condition_0"  "A.condition_1"  "A.condition_2"  "A.condition_3"  "A.condition_4"  "A.condition_5"  "A.condition_6"  "A.condition_7"  "A.condition_8"
 [10] "A.condition_9"  "A.condition_10" "A.condition_11" "A.condition_12" "A.condition_13" "A.condition_14" "A.condition_15"`


It appears that the code is changing the name of some of the sectors, but not the others.

The mapRes is

 > mapRes
       A.condition    B.condition similarity regroup
 1   A.condition_5  B.condition_4       0.65       1
 2   A.condition_4  B.condition_3       0.63       2
 3   A.condition_3  B.condition_2       0.62       3
 4   A.condition_6  B.condition_8       0.61       4
 5  A.condition_13 B.condition_14       0.60       5
 6   A.condition_1  B.condition_1       0.60       6
 7   A.condition_2  B.condition_0       0.58       7
 8   A.condition_8  B.condition_7       0.55       8
 9   A.condition_0  B.condition_6       0.55       9
 10 A.condition_12 B.condition_11       0.54      10
 11 A.condition_10 B.condition_12       0.40      11
 12  A.condition_9  B.condition_9       0.40      12
 13 A.condition_11 B.condition_10       0.30      13
 14 A.condition_14           <NA>         NA      14
 15 A.condition_15           <NA>         NA      15
 16  A.condition_7           <NA>         NA      16
 17           <NA> B.condition_13         NA      17
 18           <NA>  B.condition_5         NA      18


Thank you,

―

**Comment by omaryaghi2** [comment]
Hi Xin,

I recently tried your package and I get the exact same error as danielruss:
Error in highlight.sector(paste0(n, "_", names(cell_perc_list[[n]])),  : 
  `chr` contains index that does not beling to available sectors.

Any chance you've looked into the code for the circos plot?

Thanks,
Omar

**Comment by xgaoo** [comment]
Hi Omar and  danielruss,
Thank you for using my package. I have updated the code by adding an option of delimiter in circos_map, which should be the same as in mapRes. Please try again and let me know if there is any problem. 

Thanks,
Xin

**Comment by omaryaghi2** [comment]
Hi Xin,

Thanks for your quick response! I re-installed ClusterMap and tried again and unfortunately got the same error. It seems to be correctly outputting the cluster dendrogram, heatmap, and ape.tree, but the circos plot is incomplete (see below). Thanks for your help. 

Best,
Omar

![sc_d0_0 5_merged circos](https://user-images.githubusercontent.com/42853469/48494945-e5eba280-e7fc-11e8-863d-31c5b9142daf.png)

**Comment by xgaoo** [comment]
Hi Omar,
Could you please show me the exact command you ran? As well as the mapRes result?
Thanks,
Xin

**Comment by omaryaghi2** [comment]
Hi Xin,

Here is my code:

marker_file_list <- c(D0 = "Day0_pos_cluster_markers.csv", D0.5 = "Day0.5_pos_cluster_markers.csv")
fList <- c(D0 = "D0.RDS", D0.5 = "D0.5.RDS", sc_D0_D0.5_merged = "sc_D0_0.5_merged.RDS")
objList <- lapply(fList, readRDS)
single_obj_list <- c(D0 = objList$D0, D0.5 = objList$D0.5)
res <- cluster_map(marker_file_list, edge_cutoff = 0.1, output = "sc_D0_0.5_merged", single_obj_list = single_obj_list, comb_obj = objList$sc_D0_D0.5_merged)

Here is the mapRes result:
![image](https://user-images.githubusercontent.com/42853469/48668728-5c68f880-eaba-11e8-93b5-dc2396a85295.png)

Thanks for your help!
Omar

**Comment by xgaoo** [comment]
Hi Omar,
Thank you for the details. I think it is due to the "." in the condition name. It is fixed this time. Please try again.

best,
Xin

**Comment by omaryaghi2** [comment]
Hi Xin,

Unfortunately I'm still getting the same error, however, I think I know why. Please see the attached document which shows the state of the environment right before the error (in particular pages 4 and 5). It does seem to be because of the "." in the condition name but I don't think that the current code completely corrects for that (as the "." is inserted in the incorrect place with sub("\\.", comb_delim, names(test)).

Thanks!
Omar


[ClusterMap_Variables.docx](https://github.com/xgaoo/ClusterMap/files/2596164/ClusterMap_Variables.docx)

**Comment by omaryaghi2** [comment]
Hi Xin,

I removed all the "." in my condition names and it works well! Thanks for your help!

Best,
Omar

**Comment by xgaoo** [comment]
Hi Omar,
I fixed it last time. It can work with "." in the names. You just need to download and re-install the package. Sorry for the inconvenience.
thanks,
Xin
